export const FETCH_MENU_REQ_START = 'FETCH_MENU_REQ_START';
export const FETCH_MENU_REQ_SUCCESS = 'FETCH_MENU_REQ_SUCCESS';
export const FETCH_MENU_REQ_ERR = 'FETCH_MENU_REQ_ERR';

export const FETCH_CATEGORY_REQ_START  = 'FETCH_CATEGORY_REQ_START';
export const EETCH_CATEGORY_REQ_SUCC = 'EETCH_CATEGORY_REQ_SUCC';
export const FETCH_CATEGORY_REQ_ERR = 'FETCH_CATEGORY_REQ_ERR';
export const SET_CATEGORY = 'SET_CATEGORY';
export const ADD_TO_CART = 'ADD_TO_CART';

export const AAA_REQ_START = 'AAA_REQ_START';
export const AAA_REQ_SUCCESS = 'AAA_REQ_SUCCESS';
export const AAA_MENU_REQ_ERR = 'AAA_REQ_ERR';

export const ADD_ADDRESS = "ADD_ADDRESS";